#!/bin/bash
# Gestion du ventilateur RapsberryPi en fonction de la température
configPath="/usr/local/lib"
source ${configPath}/help.cnf
source ${configPath}/fancontrol.cnf

DEBUG=0

while [ "$#" -gt 0 ]; do
    case "$1" in
	"--help"|"-h")
		# HELP
		echo "${bold}Script de gestion du ventilateur sur RaspberryPi${normal}"
		echo "Fichier de configuration : ${configPath}/fancontrol.cnf"
		echo "Utilisation : fancontrol [OPTION]"
		echo
		echo "	${bold}--help|-h	:${normal} Afficher la présente aide"
		echo "	${bold}--debug|-d	:${normal} Mode de debuggage"
		echo "	${bold}--stop|-s	:${normal} Arrêter le ventilateur et le suivi de température CPU"
		echo "	${bold}--start|-S	:${normal} (comportement par défaut) Démarrer le suivi de température CPU et le ventilateur si nécessaire"
		echo "	${bold}--restart|-r|-R	=${normal} Arrêter le ventilateur et redémarrer le service"
		echo

		exit 0
		;;

	"-debug"|"-d")
		DEBUG=1
		;;

	"--stop"|"-s")
		# STOP FAN AND TEMP CONTROL
		gpio pwm $FAN_PIN 0
		gpio mode $FAN_PIN OUT
		gpio write $FAN_PIN 0

		exit 0
		;;

	"--restart"|"-r"|"-R")
		# RESTART FAN CONTROL
		gpio pwm $FAN_PIN 0
		# continue to start
		;;

	"--start"|"-S")
		# START FAN CONTROL (go to end of script)
                echo "Démarrage du ventilateur à $TEMP_V1°C à $((100*$PWM_V1/1024))%"
                echo "Deuxième vitesse à $TEMP_V2°C à $((100*$PWM_V2/1024))%"
                echo "Troisième vitesse à $TEMP_V3°C à $((100*$PWM_V3/1024))%"
		echo "Alarme à $TEMP_ALARM°C"
		echo
		;;

	*)
		echo "Commande $1 inconnue, tapez -h pour obtenir de l'aide"
		exit 0
		;;
    esac
    shift
done

if [ $DEBUG -gt 0 ]; then
	echo "Initialisation du ventilateur à la pin $FAN_PIN"
	echo "Vitesse nulle"
fi
gpio mode $FAN_PIN pwm
gpio pwm $FAN_PIN 0
state=0
timer=60

while [ 1 ]; do
	temp=$(($(</sys/class/thermal/thermal_zone0/temp)/1000))
	echo "Température actuelle : ${temp}°C"
	if [ $DEBUG -gt 0 ]; then
		echo "Actuellement sur la vitesse $state"
	fi

	case 1 in
	    $(($temp<= $TEMP_V1)))
		if [ $state -gt 0 ]; then
			echo "Extinction du ventilateur"
			gpio pwm $FAN_PIN 0
			state=0
			timer=60
		fi
		;;

	    $(($temp<= $TEMP_V2)))
		if [ ! $state -eq 1 ]; then
			echo "Ventilateur à la vitesse 1"
			gpio pwm $FAN_PIN $PWM_V1
			state=1
			timer=30
		fi
		;;

	    $(($temp<= $TEMP_V3)))
		if [ ! $state -eq 2 ]; then
			echo "Ventilateur à la vitesse 2"
			gpio pwm $FAN_PIN $PWM_V2
			state=2
			timer=10
		fi
		;;

	    *)
		if [ $state -lt 3 ]; then
			echo "Ventilateur à la vitesse maximale"
			gpio pwm 1 $PWM_V3
			timer=5
			if [ $temp -gt  $TEMP_ALARM ]; then
				echo "Niveau critique atteint"
				# activer l'alarme
				state=4
			else
			    if [ $state -eq 4 ]; then
				# arrêter l'alarme
				state=3
			    fi
			fi
		fi
		;;

	esac

	if [ $DEBUG -gt 0 ]; then
		echo "Prochaine mesure dans ${timer}s..."
	fi
	sleep $timer
done
exit 0
