#!/bin/bash
# Gestion du ventilateur RapsberryPi en fonction de la température
configPath="/usr/local/lib"
source ${configPath}/help.cnf
source ${configPath}/fancontrol.cnf
# cut floating point
TEMP_V1=${TEMP_V1#*.}
TEMP_V2=${TEMP_V2#*.}
TEMP_V3=${TEMP_V3#*.}
TEMP_ALARM=${TEMP_ALARM#*.}
HYST=${HYST#*.}

DEBUG=0

while [ "$#" -gt 0 ]; do
    case "$1" in
	"--help"|"-h")
		# HELP
		echo "${bold}Script de gestion du ventilateur sur RaspberryPi${normal}"
		echo "Fichier de configuration : ${configPath}/fancontrol.cnf"
		echo "Utilisation : fancontrol [OPTION]"
		echo
		echo "	${bold}--help|-h	:${normal} Afficher la présente aide"
		echo "	${bold}--debug|-d	:${normal} Mode de debuggage"
		echo "	${bold}--stop|-s	:${normal} Arrêter le ventilateur et le suivi de température CPU"
		echo "	${bold}--start|-S	:${normal} (comportement par défaut) Démarrer le suivi de température CPU et le ventilateur si nécessaire"
		echo "	${bold}--restart|-r|-R	=${normal} Arrêter le ventilateur et redémarrer le service"
		echo

		exit 0
		;;

	"-debug"|"-d")
		DEBUG=1
		;;

	"--stop"|"-s")
		# STOP FAN AND TEMP CONTROL
		gpio pwm $FAN_PIN 0
		gpio mode $FAN_PIN OUT
		gpio write $FAN_PIN 0

		exit 0
		;;

	"--restart"|"-r"|"-R")
		# RESTART FAN CONTROL
		gpio pwm $FAN_PIN 0
		# continue to start
		;;

	"--start"|"-S")
		# START FAN CONTROL (go to end of script)
                echo "Démarrage du ventilateur à $TEMP_V1°C à $((100*$PWM_V1/1024))%"
                echo "Deuxième vitesse à $TEMP_V2°C à $((100*$PWM_V2/1024))%"
                echo "Troisième vitesse à $TEMP_V3°C à $((100*$PWM_V3/1024))%"
		echo "Alarme à $TEMP_ALARM°C"
		echo
		;;

	*)
		echo "Commande $1 inconnue, tapez -h pour obtenir de l'aide"
		exit 0
		;;
    esac
    shift
done

set_fan ()
{
	if [ ! $# -eq 1 ]; then
		return 127
	fi
	newState=$1
	case $newState in
		0)
			gpio pwm $FAN_PIN 0
			timer=60
			;;
		1)
			gpio pwm $FAN_PIN $PWM_V1
			timer=30
			;;
		2)
			gpio pwm $FAN_PIN $PWM_V2
			timer=10
			;;
		3|4)
			gpio pwm $FAN_PIN $PWM_V3
			timer=5
			if [ newState -eq 4 ]; then
				# activer l'alarme
				gpio write $ALARM_PIN 1
			else
				# eteindre l'alarme
				gpio write $ALARM_PIN 0
			fi
			;;
		*)
			return 127
			;;
	esac
	
	state=$newState
	if [ $state -gt 0 ]; then
		echo "Ventilateur à la vitesse $state"
	else echo "Extinction du ventilateur"
	fi
	return 0
}

if [ $DEBUG -gt 0 ]; then
	echo "Initialisation du ventilateur à la pin $FAN_PIN"
	echo "Vitesse nulle"
fi
gpio mode $FAN_PIN pwm
gpio pwm $FAN_PIN 0
state=0
timer=60

while [ 1 ]; do
	temp=$(($(</sys/class/thermal/thermal_zone0/temp)/1000))
	echo "Température actuelle : ${temp}°C"
	if [ $DEBUG -gt 0 ]; then
		echo "Actuellement sur la vitesse $state"
	fi

	minusTemp=$(($temp-$HYST))
	majorTemp=$(($temp+$HYST))
	case $state in
		0)
			if [ $minusTemp -lt $TEMP_V1 ]; then
				if [ $DEBUG -gt 0 ]; then echo "Pas de changement"; fi
			elif [ $minusTemp -lt $TEMP_V2 ]; then
				set_fan 1
			elif [ $minusTemp -lt $TEMP_V3 ]; then
				set_fan 2
			elif [ $minusTemp -lt $TEMP_ALARM ]; then
				set_fan 3
			else set_fan 4
			fi
			;;
			
		1)
			if [ $majorTemp -lt $TEMP_V1 ]; then
				set_fan 0
			elif [ $minusTemp -lt $TEMP_V2 ]; then
				if [ $DEBUG -gt 0 ]; then echo "Pas de changement"; fi
			elif [ $minusTemp -lt $TEMP_V3 ]; then
				set_fan 2
			elif [ $minusTemp -lt $TEMP_ALARM ]; then
				set_fan 3
			else set_fan 4
			fi
			;;
			
		2)
			if [ $majorTemp -lt $TEMP_V1 ]; then
				set_fan 0
			elif [ $majorTemp -lt $TEMP_V2 ]; then
				set_fan 1
			elif [ $minusTemp -lt $TEMP_V3 ]; then
				if [ $DEBUG -gt 0 ]; then echo "Pas de changement"; fi
			elif [ $minusTemp -lt $TEMP_ALARM ]; then
				set_fan 3
			else set_fan 4
			fi
			;;

		3)
			if [ $majorTemp -lt $TEMP_V1 ]; then
				set_fan 0
			elif [ $majorTemp -lt $TEMP_V2 ]; then
				set_fan 1
			elif [ $majorTemp -lt $TEMP_V3 ]; then
				set_fan 2
			elif [ $minusTemp -lt $TEMP_ALARM ]; then
				if [ $DEBUG -gt 0 ]; then echo "Pas de changement"; fi
			else set_fan 4
			fi
			;;
			
		4)
			if [ $majorTemp -lt $TEMP_V1 ]; then
				set_fan 0
			elif [ $majorTemp -lt $TEMP_V2 ]; then
				set_fan 1
			elif [ $majorTemp -lt $TEMP_V3 ]; then
				set_fan 2
			elif [ $majorTemp -lt $TEMP_ALARM ]; then
				set_fan 3
			elif [ $DEBUG -gt 0 ]; then echo "Pas de changement"; fi
			fi
			;;
		
		*)
			if [ $DEBUG -gt 0 ]; then echo "Etat inconnu, vitesse maximale par sécurité"; fi
			set_fan 3
			;;
	esac

	if [ $DEBUG -gt 0 ]; then
		echo "Prochaine mesure dans ${timer}s..."
	fi
	
	sleep $timer
done
exit 0
